//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelInfo", Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
    [System.SerializableAttribute()]
    public partial class ModelInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelBarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelBarCode {
            get {
                return this.ModelBarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelBarCodeField, value) != true)) {
                    this.ModelBarCodeField = value;
                    this.RaisePropertyChanged("ModelBarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecondModelInfo", Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
    [System.SerializableAttribute()]
    public partial class SecondModelInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondModelBarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondModelPinghaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondModelBarCode {
            get {
                return this.SecondModelBarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondModelBarCodeField, value) != true)) {
                    this.SecondModelBarCodeField = value;
                    this.RaisePropertyChanged("SecondModelBarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondModelName {
            get {
                return this.SecondModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondModelNameField, value) != true)) {
                    this.SecondModelNameField = value;
                    this.RaisePropertyChanged("SecondModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondModelPinghao {
            get {
                return this.SecondModelPinghaoField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondModelPinghaoField, value) != true)) {
                    this.SecondModelPinghaoField = value;
                    this.RaisePropertyChanged("SecondModelPinghao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelInfoWithSecondModelInfo", Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
    [System.SerializableAttribute()]
    public partial class ModelInfoWithSecondModelInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelBarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StudyTest.ServiceReference1.SecondModelInfo[] SecondModelInfoListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelBarCode {
            get {
                return this.ModelBarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelBarCodeField, value) != true)) {
                    this.ModelBarCodeField = value;
                    this.RaisePropertyChanged("ModelBarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName {
            get {
                return this.ModelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelNameField, value) != true)) {
                    this.ModelNameField = value;
                    this.RaisePropertyChanged("ModelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudyTest.ServiceReference1.SecondModelInfo[] SecondModelInfoList {
            get {
                return this.SecondModelInfoListField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondModelInfoListField, value) != true)) {
                    this.SecondModelInfoListField = value;
                    this.RaisePropertyChanged("SecondModelInfoList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetModelInfoByWorkNum", ReplyAction="http://tempuri.org/IService1/GetModelInfoByWorkNumResponse")]
        StudyTest.ServiceReference1.ModelInfo GetModelInfoByWorkNum(int workNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetModelInfoByWorkNum", ReplyAction="http://tempuri.org/IService1/GetModelInfoByWorkNumResponse")]
        System.Threading.Tasks.Task<StudyTest.ServiceReference1.ModelInfo> GetModelInfoByWorkNumAsync(int workNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSecondModelInfoByModelInfoBarcode", ReplyAction="http://tempuri.org/IService1/GetSecondModelInfoByModelInfoBarcodeResponse")]
        StudyTest.ServiceReference1.SecondModelInfo[] GetSecondModelInfoByModelInfoBarcode(string modelInfoBarcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSecondModelInfoByModelInfoBarcode", ReplyAction="http://tempuri.org/IService1/GetSecondModelInfoByModelInfoBarcodeResponse")]
        System.Threading.Tasks.Task<StudyTest.ServiceReference1.SecondModelInfo[]> GetSecondModelInfoByModelInfoBarcodeAsync(string modelInfoBarcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetModelInfoWithSecondModelInfoByWorkNum", ReplyAction="http://tempuri.org/IService1/GetModelInfoWithSecondModelInfoByWorkNumResponse")]
        StudyTest.ServiceReference1.ModelInfoWithSecondModelInfo GetModelInfoWithSecondModelInfoByWorkNum(int workNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetModelInfoWithSecondModelInfoByWorkNum", ReplyAction="http://tempuri.org/IService1/GetModelInfoWithSecondModelInfoByWorkNumResponse")]
        System.Threading.Tasks.Task<StudyTest.ServiceReference1.ModelInfoWithSecondModelInfo> GetModelInfoWithSecondModelInfoByWorkNumAsync(int workNum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : StudyTest.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<StudyTest.ServiceReference1.IService1>, StudyTest.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudyTest.ServiceReference1.ModelInfo GetModelInfoByWorkNum(int workNum) {
            return base.Channel.GetModelInfoByWorkNum(workNum);
        }
        
        public System.Threading.Tasks.Task<StudyTest.ServiceReference1.ModelInfo> GetModelInfoByWorkNumAsync(int workNum) {
            return base.Channel.GetModelInfoByWorkNumAsync(workNum);
        }
        
        public StudyTest.ServiceReference1.SecondModelInfo[] GetSecondModelInfoByModelInfoBarcode(string modelInfoBarcode) {
            return base.Channel.GetSecondModelInfoByModelInfoBarcode(modelInfoBarcode);
        }
        
        public System.Threading.Tasks.Task<StudyTest.ServiceReference1.SecondModelInfo[]> GetSecondModelInfoByModelInfoBarcodeAsync(string modelInfoBarcode) {
            return base.Channel.GetSecondModelInfoByModelInfoBarcodeAsync(modelInfoBarcode);
        }
        
        public StudyTest.ServiceReference1.ModelInfoWithSecondModelInfo GetModelInfoWithSecondModelInfoByWorkNum(int workNum) {
            return base.Channel.GetModelInfoWithSecondModelInfoByWorkNum(workNum);
        }
        
        public System.Threading.Tasks.Task<StudyTest.ServiceReference1.ModelInfoWithSecondModelInfo> GetModelInfoWithSecondModelInfoByWorkNumAsync(int workNum) {
            return base.Channel.GetModelInfoWithSecondModelInfoByWorkNumAsync(workNum);
        }
    }
}
