//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CommonTypeConfigS
    {
        public int ID { get; set; }
        public int No { get; set; }
        public string ItemName { get; set; }
        public int CommonTypeConn { get; set; }
        public int Edit { get; set; }
        public System.DateTime EditTime { get; set; }
    
        public virtual TB_CommonTypeConfigM TB_CommonTypeConfigM { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
