//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Components
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Components()
        {
            this.TB_MatComSuplConn = new HashSet<TB_MatComSuplConn>();
        }
    
        public int ID { get; set; }
        public string ComponentsCode { get; set; }
        public string ComponentsName { get; set; }
        public string Guigexinghao { get; set; }
        public string Tuyangdaihao { get; set; }
        public string Fenleibianma { get; set; }
        public string Fenleimingcheng { get; set; }
        public double Jihuajia { get; set; }
        public double Zuixinchengben { get; set; }
        public int Jiandangren { get; set; }
        public System.DateTime Qiyongriqi { get; set; }
        public System.DateTime Zhuxiaoriqi { get; set; }
        public int Genggairen { get; set; }
        public System.DateTime Genggairiqi { get; set; }
        public string FenleibianmaConn { get; set; }
        public string Beizhu { get; set; }
    
        public virtual TB_Fenleibianma TB_Fenleibianma { get; set; }
        public virtual TB_User TB_User { get; set; }
        public virtual TB_User TB_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MatComSuplConn> TB_MatComSuplConn { get; set; }
    }
}
