//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_KeyComponentsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_KeyComponentsInfo()
        {
            this.TB_MatCodeKeyComLink = new HashSet<TB_MatCodeKeyComLink>();
        }
    
        public int ID { get; set; }
        public string KeyComponentsName { get; set; }
        public string AssistManufacturers { get; set; }
        public string Remark { get; set; }
        public int Recorder { get; set; }
        public System.DateTime RecordDate { get; set; }
    
        public virtual TB_User TB_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MatCodeKeyComLink> TB_MatCodeKeyComLink { get; set; }
    }
}
