//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MatComSuplConn
    {
        public int ID { get; set; }
        public string MatCode { get; set; }
        public int ComponentsConn { get; set; }
        public int SupplierConn { get; set; }
        public int Editor { get; set; }
        public System.DateTime EditorTime { get; set; }
    
        public virtual TB_Components TB_Components { get; set; }
        public virtual TB_Supplier TB_Supplier { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
