//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ProductionPlanFromERP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ProductionPlanFromERP()
        {
            this.TB_MonthPlanForLED = new HashSet<TB_MonthPlanForLED>();
        }
    
        public int ID { get; set; }
        public string MatType { get; set; }
        public int PlanAmount { get; set; }
        public System.DateTime PlanBeginTime { get; set; }
        public System.DateTime PlanEndTime { get; set; }
        public string PlanDepartment { get; set; }
        public Nullable<int> CompleteAmount { get; set; }
        public string CompleteStatus { get; set; }
        public int ImportUser { get; set; }
        public System.DateTime ImportDate { get; set; }
    
        public virtual TB_MaterialInfo TB_MaterialInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MonthPlanForLED> TB_MonthPlanForLED { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
