//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PalletInfo
    {
        public string PalletCode { get; set; }
        public string PalletSize { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public string Remark { get; set; }
    }
}
