//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PLCAdressWithStopper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PLCAdressWithStopper()
        {
            this.TB_PLCBaseAdressInfo = new HashSet<TB_PLCBaseAdressInfo>();
        }
    
        public int ID { get; set; }
        public string StopperName { get; set; }
        public string StopperCode { get; set; }
        public string PalletCode { get; set; }
        public string ToPositCode { get; set; }
        public string StopperLockForWorkStation { get; set; }
        public string StopperLockForNextStopper { get; set; }
        public Nullable<int> No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PLCBaseAdressInfo> TB_PLCBaseAdressInfo { get; set; }
    }
}
