//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ProcessRouteP
    {
        public int ID { get; set; }
        public string ProcessRouteM { get; set; }
        public Nullable<int> No { get; set; }
        public Nullable<int> ProcessRouteMID { get; set; }
        public int WorkStationID { get; set; }
        public bool IsUse { get; set; }
        public bool IsLast { get; set; }
        public string Remark { get; set; }
    
        public virtual TB_ProcessRouteM TB_ProcessRouteM { get; set; }
        public virtual TB_WorkStationInfo TB_WorkStationInfo { get; set; }
    }
}
