//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PLCAdressWithWorkStationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PLCAdressWithWorkStationInfo()
        {
            this.TB_SecondWorkStationInfo = new HashSet<TB_SecondWorkStationInfo>();
        }
    
        public int PositCode { get; set; }
        public string OrderNo { get; set; }
        public string PalletCode { get; set; }
        public string ToPositCode { get; set; }
        public string ScanPalletCode { get; set; }
        public string PositCodeLock { get; set; }
        public string PalletCode2 { get; set; }
        public string ToPositCode2 { get; set; }
        public string RequirePallet { get; set; }
        public string ReleasePallet { get; set; }
        public string ConfirmPalletArrived { get; set; }
        public Nullable<int> SecondWorkStationID { get; set; }
        public string PositCodeDemand { get; set; }
        public string PositCodeConfirm { get; set; }
        public string PositCodeSecede { get; set; }
        public string ErrorMessage { get; set; }
        public string IsUse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SecondWorkStationInfo> TB_SecondWorkStationInfo { get; set; }
    }
}
