//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ProductionPlan
    {
        public int ID { get; set; }
        public string MaterialID { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int Planner { get; set; }
        public System.DateTime PlanTime { get; set; }
        public string LineNumber { get; set; }
        public Nullable<int> CompleteAmount { get; set; }
        public string CompleteStatus { get; set; }
    
        public virtual TB_MaterialInfo TB_MaterialInfo { get; set; }
        public virtual TB_User TB_User { get; set; }
    }
}
