//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_User()
        {
            this.TB_CommonTypeConfigM = new HashSet<TB_CommonTypeConfigM>();
            this.TB_CommonTypeConfigS = new HashSet<TB_CommonTypeConfigS>();
            this.TB_Components = new HashSet<TB_Components>();
            this.TB_Components1 = new HashSet<TB_Components>();
            this.TB_Exception = new HashSet<TB_Exception>();
            this.TB_Fenleibianma = new HashSet<TB_Fenleibianma>();
            this.TB_KeyComponentsInfo = new HashSet<TB_KeyComponentsInfo>();
            this.TB_LoginRecord = new HashSet<TB_LoginRecord>();
            this.TB_MatCodeKeyComLink = new HashSet<TB_MatCodeKeyComLink>();
            this.TB_MatComSuplConn = new HashSet<TB_MatComSuplConn>();
            this.TB_MaterialInfo = new HashSet<TB_MaterialInfo>();
            this.TB_MaterialInfo1 = new HashSet<TB_MaterialInfo>();
            this.TB_ProcessRouteM = new HashSet<TB_ProcessRouteM>();
            this.TB_ProductionPlan = new HashSet<TB_ProductionPlan>();
            this.TB_ProductionPlanFromERP = new HashSet<TB_ProductionPlanFromERP>();
            this.TB_QCRecord = new HashSet<TB_QCRecord>();
            this.TB_RepairRecord = new HashSet<TB_RepairRecord>();
            this.TB_ScanRecord = new HashSet<TB_ScanRecord>();
            this.TB_Supplier = new HashSet<TB_Supplier>();
            this.TB_Supplier1 = new HashSet<TB_Supplier>();
            this.TB_SystemLog = new HashSet<TB_SystemLog>();
            this.TB_UserLoginRight = new HashSet<TB_UserLoginRight>();
            this.TB_WorkDtl = new HashSet<TB_WorkDtl>();
            this.TB_WorkException = new HashSet<TB_WorkException>();
            this.TB_WorkDtlForEachStation = new HashSet<TB_WorkDtlForEachStation>();
            this.TB_WorkMain = new HashSet<TB_WorkMain>();
            this.TB_WorkMain1 = new HashSet<TB_WorkMain>();
            this.TB_WorkTime = new HashSet<TB_WorkTime>();
            this.TB_WorkTimeBandingInfo = new HashSet<TB_WorkTimeBandingInfo>();
            this.TB_WorkTimeBandingInfo1 = new HashSet<TB_WorkTimeBandingInfo>();
            this.TB_WorkTimeM = new HashSet<TB_WorkTimeM>();
            this.TB_WorkTimeS = new HashSet<TB_WorkTimeS>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserID { get; set; }
        public string UserLevel { get; set; }
        public string Department { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string HouseAddress { get; set; }
        public Nullable<int> WorkClassesID { get; set; }
        public bool IsUse { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CommonTypeConfigM> TB_CommonTypeConfigM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CommonTypeConfigS> TB_CommonTypeConfigS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Components> TB_Components { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Components> TB_Components1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Exception> TB_Exception { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Fenleibianma> TB_Fenleibianma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_KeyComponentsInfo> TB_KeyComponentsInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LoginRecord> TB_LoginRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MatCodeKeyComLink> TB_MatCodeKeyComLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MatComSuplConn> TB_MatComSuplConn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MaterialInfo> TB_MaterialInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MaterialInfo> TB_MaterialInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProcessRouteM> TB_ProcessRouteM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductionPlan> TB_ProductionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductionPlanFromERP> TB_ProductionPlanFromERP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_QCRecord> TB_QCRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RepairRecord> TB_RepairRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ScanRecord> TB_ScanRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Supplier> TB_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Supplier> TB_Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SystemLog> TB_SystemLog { get; set; }
        public virtual TB_WorkClasses TB_WorkClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_UserLoginRight> TB_UserLoginRight { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkDtl> TB_WorkDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkException> TB_WorkException { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkDtlForEachStation> TB_WorkDtlForEachStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkMain> TB_WorkMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkMain> TB_WorkMain1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTime> TB_WorkTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTimeBandingInfo> TB_WorkTimeBandingInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTimeBandingInfo> TB_WorkTimeBandingInfo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTimeM> TB_WorkTimeM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTimeS> TB_WorkTimeS { get; set; }
    }
}
