//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkDtlForEachStation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WorkDtlForEachStation()
        {
            this.TB_QCRecord = new HashSet<TB_QCRecord>();
        }
    
        public int ID { get; set; }
        public Nullable<int> WorkMainID { get; set; }
        public Nullable<int> SecondWorkStationID { get; set; }
        public Nullable<int> WorkMen { get; set; }
        public Nullable<System.DateTime> WorkBeginTime { get; set; }
        public Nullable<System.DateTime> WorkEndTime { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_QCRecord> TB_QCRecord { get; set; }
        public virtual TB_SecondWorkStationInfo TB_SecondWorkStationInfo { get; set; }
        public virtual TB_User TB_User { get; set; }
        public virtual TB_WorkMain TB_WorkMain { get; set; }
    }
}
