//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkTimeS
    {
        public int ID { get; set; }
        public int WorkTimeMConn { get; set; }
        public int WorkFlowConn { get; set; }
        public double WorkTime { get; set; }
        public int InitFlag { get; set; }
        public string Remark { get; set; }
        public int Editor { get; set; }
        public System.DateTime EditorTime { get; set; }
    
        public virtual TB_User TB_User { get; set; }
        public virtual TB_WorkStationInfo TB_WorkStationInfo { get; set; }
        public virtual TB_WorkTimeM TB_WorkTimeM { get; set; }
    }
}
