//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkTimeM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WorkTimeM()
        {
            this.TB_MaterialInfo = new HashSet<TB_MaterialInfo>();
            this.TB_WorkTimeS = new HashSet<TB_WorkTimeS>();
        }
    
        public int ID { get; set; }
        public string WorkTimeMName { get; set; }
        public string Remark { get; set; }
        public int Editor { get; set; }
        public System.DateTime EditorTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MaterialInfo> TB_MaterialInfo { get; set; }
        public virtual TB_User TB_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTimeS> TB_WorkTimeS { get; set; }
    }
}
