//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WorkDtl()
        {
            this.TB_RepairRecord = new HashSet<TB_RepairRecord>();
            this.TB_ScanRecord = new HashSet<TB_ScanRecord>();
            this.TB_WorkException = new HashSet<TB_WorkException>();
        }
    
        public int ID { get; set; }
        public int WorkMainID { get; set; }
        public string PalletCode { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsException { get; set; }
        public Nullable<int> WorkStatus { get; set; }
        public Nullable<int> ExceptionSecondWorkStationID { get; set; }
        public Nullable<int> WorkStatusEditor { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
    
        public virtual TB_Exception TB_Exception { get; set; }
        public virtual TB_MaterialInfo TB_MaterialInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RepairRecord> TB_RepairRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ScanRecord> TB_ScanRecord { get; set; }
        public virtual TB_SecondWorkStationInfo TB_SecondWorkStationInfo { get; set; }
        public virtual TB_User TB_User { get; set; }
        public virtual TB_WorkMain TB_WorkMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkException> TB_WorkException { get; set; }
    }
}
