//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkClasses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WorkClasses()
        {
            this.TB_User = new HashSet<TB_User>();
        }
    
        public int ID { get; set; }
        public string ClassName { get; set; }
        public string ClassCode { get; set; }
        public Nullable<System.DateTime> WorkBeginTime { get; set; }
        public Nullable<System.DateTime> WorkEndTime { get; set; }
        public Nullable<int> WorkerNumber { get; set; }
        public Nullable<int> NumberClassPerDay { get; set; }
        public string PersonInCharge { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_User> TB_User { get; set; }
    }
}
