//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkStationInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WorkStationInfo()
        {
            this.TB_ProcessRouteP = new HashSet<TB_ProcessRouteP>();
            this.TB_SecondWorkStationInfo = new HashSet<TB_SecondWorkStationInfo>();
            this.TB_WorkTimeS = new HashSet<TB_WorkTimeS>();
        }
    
        public int ID { get; set; }
        public string WorkStationCode { get; set; }
        public string WorkStationName { get; set; }
        public string AddressCode { get; set; }
        public string TypeCode { get; set; }
        public string WorkTimePerClass { get; set; }
        public string NumberClassPerDay { get; set; }
        public string SecondWorkStationCode { get; set; }
        public string WorkStationStatu { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProcessRouteP> TB_ProcessRouteP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SecondWorkStationInfo> TB_SecondWorkStationInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkTimeS> TB_WorkTimeS { get; set; }
    }
}
