//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_WorkMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_WorkMain()
        {
            this.TB_WorkDtl = new HashSet<TB_WorkDtl>();
            this.TB_WorkDtlForEachStation = new HashSet<TB_WorkDtlForEachStation>();
        }
    
        public int WorkID { get; set; }
        public Nullable<int> WorkMainID { get; set; }
        public string PalletCode { get; set; }
        public bool IsCommit { get; set; }
        public Nullable<int> Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Finished { get; set; }
        public Nullable<int> FinishedMen { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public string FinishedType { get; set; }
        public int SecondWorkStationIDForNew { get; set; }
        public Nullable<int> SecondWorkStationIDForComplete { get; set; }
    
        public virtual TB_SecondWorkStationInfo TB_SecondWorkStationInfo { get; set; }
        public virtual TB_SecondWorkStationInfo TB_SecondWorkStationInfo1 { get; set; }
        public virtual TB_User TB_User { get; set; }
        public virtual TB_User TB_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkDtl> TB_WorkDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_WorkDtlForEachStation> TB_WorkDtlForEachStation { get; set; }
    }
}
