//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace StudyTest.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetModelInfoByWorkNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSecondModelInfoByModelInfoBarcodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetModelInfoWithSecondModelInfoByWorkNumOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::StudyTest.Properties.Settings.Default.StudyTest_WebReference_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetModelInfoByWorkNumCompletedEventHandler GetModelInfoByWorkNumCompleted;
        
        /// <remarks/>
        public event GetSecondModelInfoByModelInfoBarcodeCompletedEventHandler GetSecondModelInfoByModelInfoBarcodeCompleted;
        
        /// <remarks/>
        public event GetModelInfoWithSecondModelInfoByWorkNumCompletedEventHandler GetModelInfoWithSecondModelInfoByWorkNumCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetModelInfoByWorkNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ModelInfo GetModelInfoByWorkNum(int workNum, [System.Xml.Serialization.XmlIgnoreAttribute()] bool workNumSpecified) {
            object[] results = this.Invoke("GetModelInfoByWorkNum", new object[] {
                        workNum,
                        workNumSpecified});
            return ((ModelInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetModelInfoByWorkNumAsync(int workNum, bool workNumSpecified) {
            this.GetModelInfoByWorkNumAsync(workNum, workNumSpecified, null);
        }
        
        /// <remarks/>
        public void GetModelInfoByWorkNumAsync(int workNum, bool workNumSpecified, object userState) {
            if ((this.GetModelInfoByWorkNumOperationCompleted == null)) {
                this.GetModelInfoByWorkNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModelInfoByWorkNumOperationCompleted);
            }
            this.InvokeAsync("GetModelInfoByWorkNum", new object[] {
                        workNum,
                        workNumSpecified}, this.GetModelInfoByWorkNumOperationCompleted, userState);
        }
        
        private void OnGetModelInfoByWorkNumOperationCompleted(object arg) {
            if ((this.GetModelInfoByWorkNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModelInfoByWorkNumCompleted(this, new GetModelInfoByWorkNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetSecondModelInfoByModelInfoBarcode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
        public SecondModelInfo[] GetSecondModelInfoByModelInfoBarcode([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string modelInfoBarcode) {
            object[] results = this.Invoke("GetSecondModelInfoByModelInfoBarcode", new object[] {
                        modelInfoBarcode});
            return ((SecondModelInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSecondModelInfoByModelInfoBarcodeAsync(string modelInfoBarcode) {
            this.GetSecondModelInfoByModelInfoBarcodeAsync(modelInfoBarcode, null);
        }
        
        /// <remarks/>
        public void GetSecondModelInfoByModelInfoBarcodeAsync(string modelInfoBarcode, object userState) {
            if ((this.GetSecondModelInfoByModelInfoBarcodeOperationCompleted == null)) {
                this.GetSecondModelInfoByModelInfoBarcodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSecondModelInfoByModelInfoBarcodeOperationCompleted);
            }
            this.InvokeAsync("GetSecondModelInfoByModelInfoBarcode", new object[] {
                        modelInfoBarcode}, this.GetSecondModelInfoByModelInfoBarcodeOperationCompleted, userState);
        }
        
        private void OnGetSecondModelInfoByModelInfoBarcodeOperationCompleted(object arg) {
            if ((this.GetSecondModelInfoByModelInfoBarcodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSecondModelInfoByModelInfoBarcodeCompleted(this, new GetSecondModelInfoByModelInfoBarcodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetModelInfoWithSecondModelInfoByWorkNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ModelInfoWithSecondModelInfo GetModelInfoWithSecondModelInfoByWorkNum(int workNum, [System.Xml.Serialization.XmlIgnoreAttribute()] bool workNumSpecified) {
            object[] results = this.Invoke("GetModelInfoWithSecondModelInfoByWorkNum", new object[] {
                        workNum,
                        workNumSpecified});
            return ((ModelInfoWithSecondModelInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetModelInfoWithSecondModelInfoByWorkNumAsync(int workNum, bool workNumSpecified) {
            this.GetModelInfoWithSecondModelInfoByWorkNumAsync(workNum, workNumSpecified, null);
        }
        
        /// <remarks/>
        public void GetModelInfoWithSecondModelInfoByWorkNumAsync(int workNum, bool workNumSpecified, object userState) {
            if ((this.GetModelInfoWithSecondModelInfoByWorkNumOperationCompleted == null)) {
                this.GetModelInfoWithSecondModelInfoByWorkNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetModelInfoWithSecondModelInfoByWorkNumOperationCompleted);
            }
            this.InvokeAsync("GetModelInfoWithSecondModelInfoByWorkNum", new object[] {
                        workNum,
                        workNumSpecified}, this.GetModelInfoWithSecondModelInfoByWorkNumOperationCompleted, userState);
        }
        
        private void OnGetModelInfoWithSecondModelInfoByWorkNumOperationCompleted(object arg) {
            if ((this.GetModelInfoWithSecondModelInfoByWorkNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetModelInfoWithSecondModelInfoByWorkNumCompleted(this, new GetModelInfoWithSecondModelInfoByWorkNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
    public partial class ModelInfo {
        
        private string classField;
        
        private string modelBarCodeField;
        
        private string modelNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelBarCode {
            get {
                return this.modelBarCodeField;
            }
            set {
                this.modelBarCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
    public partial class ModelInfoWithSecondModelInfo {
        
        private string classField;
        
        private string modelBarCodeField;
        
        private string modelNameField;
        
        private SecondModelInfo[] secondModelInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelBarCode {
            get {
                return this.modelBarCodeField;
            }
            set {
                this.modelBarCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public SecondModelInfo[] SecondModelInfoList {
            get {
                return this.secondModelInfoListField;
            }
            set {
                this.secondModelInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/GreatWallWCFServer")]
    public partial class SecondModelInfo {
        
        private string secondModelBarCodeField;
        
        private string secondModelNameField;
        
        private string secondModelPinghaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondModelBarCode {
            get {
                return this.secondModelBarCodeField;
            }
            set {
                this.secondModelBarCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondModelName {
            get {
                return this.secondModelNameField;
            }
            set {
                this.secondModelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondModelPinghao {
            get {
                return this.secondModelPinghaoField;
            }
            set {
                this.secondModelPinghaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetModelInfoByWorkNumCompletedEventHandler(object sender, GetModelInfoByWorkNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModelInfoByWorkNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModelInfoByWorkNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ModelInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ModelInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSecondModelInfoByModelInfoBarcodeCompletedEventHandler(object sender, GetSecondModelInfoByModelInfoBarcodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSecondModelInfoByModelInfoBarcodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSecondModelInfoByModelInfoBarcodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SecondModelInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SecondModelInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetModelInfoWithSecondModelInfoByWorkNumCompletedEventHandler(object sender, GetModelInfoWithSecondModelInfoByWorkNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetModelInfoWithSecondModelInfoByWorkNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetModelInfoWithSecondModelInfoByWorkNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ModelInfoWithSecondModelInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ModelInfoWithSecondModelInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591